_target_: src.lightning_model.NetMultiViewLightning

# Params for PRISM_19Q4

layers_before_concat: [1024, 512, 256]
layers_after_concat: [512, 256, 128]
input_size: [18748, 256]
output_size: 1
dropout: 0.4879363265682527
activation: relu
lr: 0.0024467
max_lr: 0.0136487475429
weight_decay: 0.000709207901609
task: regression
loss_function: mse
