_target_: main_code.lightning_model.NetMultiViewLightning

# Params for PRISM_19Q4 - baseline

layers_before_concat: [1024, 512, 256]
layers_after_concat: [1024, 512, 256, 128, 64]
input_size: [18748, 256]
output_size: 1
dropout: 0.05
activation: relu
lr: 0.0001
max_lr: 0.01
weight_decay: 0.001
task: binary_classification
loss_function: bce
