_target_: src.lightning_model.Netlightning

hidden_layers: [1024, 512, 256, 128, 64]
input_size: 18748
output_size: 1
dropout: 0.2
activation: relu
lr: 0.0001
max_lr: 0.01
weight_decay: 0.05
# task: regression
loss_function: mse
