defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar

model_checkpoint:
  monitor: "val_auc_roc"
  mode: "max"
  save_last: 5

model_summary:
  max_depth: 1

fine_tune_scheduler:
  # _target_: finetuning_scheduler.FineTuningScheduler
  gen_ft_sched_only: false
  epoch_transitions_only: false
  ft_schedule: ${paths.root_dir}configs/ft_schedule.yaml
