rich_progress_bar:
  _target_: pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme
  description: "#af005f"
  progress_bar_finished: green_yellow
  batch_progress: "cyan1"
  time: "bright_red"
  metrics: "gold3"
